### ISSUE TITLE
displaying tooltips programatically

### ISSUE THREAD

**Issue by jamiewaese** [Caged/d3-tip#100]
Hate to bother you but the explicit-target example is not relevant to the question. I'm trying to trigger the tooltip from outside the d3 chart via jQuery or JavaScript. The explicit-target example demonstrates how to append the tip.show trigger onto d3 generated elements while d3 is building them, and then display the tip on a different element within the chart. I need to trigger the tip when mousing over a list of hyperlinks on a different part of the page (outside the d3 chart) that are generated with jQuery.

I can access the DOM element like this: 

`d3.select("[id=PhylomapNode15]").node()`

and it returns this:

`<circle id="PhylomapNode15" onmouseover="mouseOverNode(15)" onmouseout="mouseOutNode(15)" class="PhylomapChild" cx="145.36022983409694" cy="200" r="32.502108609236146" style="fill: rgb(0, 203, 0); stroke: rgb(128, 128, 128); stroke-width: 1px;"><title>8</title></circle>`

I'd like to add a line to my mouseOverNode(id) function that triggers the tooltip. Something like:

`d3.select("[id=PhylomapNode15]").node().tip.show`

...would be nice, but that produces an error:

`Uncaught TypeError: Cannot read property 'show' of undefined`

Any suggestions would be most appreciated. I have been struggling with this for several days.

**Comment by Caged** [comment]
>  but the explicit-target example is not relevant to the question

I'm having trouble parsing your question.  It'd be great if you could throw up some example code somewhere illustrating the problem and context.  

> I'd like to add a line to my mouseOverNode(id) function that triggers the tooltip. Something like:

Find the circle that's associated with the line once the line is hovered over and use explicit targets to invoke the tooltip.  

1. Line mouseover is triggered
2. Find circle/node associated with line where I want the tooltip to appear
3. Invoke tooltip on associated node by explicitly passing it to `tip.show` as a second argument.  `tip.show(data, node)`. 

Please don't open a new issue and instead reopen this if you have further questions or examples I can look at.

**Comment by jamiewaese** [comment]
Here is the site I'm building: 

`http://bar.utoronto.ca/~jwaese/Phylomap2/?datafile=data/Example1.nwk`

See how the tooltips appear when you mouse over any of the circles? Very nice! I also want to trigger them when you mouse over the list of items on the right, or over any of the nodes on the phyogenetic tree for that matter. 

If you open the console you can access any of the circles by typing

`d3.select("[id=PhylomapNode15]").node()`

The question is, how can you trigger the tooltip to appear over that circle from a javascript function that is not related to the d3 chart? How can I say "tip.show" from outside the d3 constructor? What is the code to trigger the tooltip directly from the console?

Thanks very much for your help. I'm sorry I couldn't describe the problem better.

**Comment by Caged** [comment]
Can you link me to the code where you initialize the tooltip?  You can't invoke a tooltip from the console unless you can access the variable storing the tooltip instance.

**Comment by jamiewaese** [comment]
The tooltip is initialized in line 70 of this: 

`http://bar.utoronto.ca/~jwaese/Phylomap2/js/CirclePacking.js`

This program builds the circle-packing chart that is inserted into a div on the index page called #Phylomap.
