### ISSUE TITLE
How to refresh tip text for bilevel partition example?

### ISSUE THREAD

**Issue by scholarworks** [Caged/d3-tip#101]
I'm using the bilevel example:  http://bl.ocks.org/mbostock/5944371 for a chart and can easily get tips working for the "name" portion of the json data, but the data is lost on the zoomout functions. 

How can I get the tips to work throughout this example and reset full zoomout?

Thanks.

**Comment by Caged** [comment]
Triaging Issues. Closing as not a bug.
