### ISSUE TITLE
Lack of document/example for CommonJS project

### ISSUE THREAD

**Issue by DreamHouse** [Caged/d3-tip#105]
It would have saved me a couple of hours if there is some instructions about how to require this module in a CommonJS project. I almost switched to other tools because I was not able to load the module.

**Comment by karstenpackmohr** [comment]
How did you do it?

**Comment by DreamHouse** [comment]
I have to require the library first, then invoke it with a d3 variable before using d3.tip(). Below is my coffeescript code:

d3tip_module = require 'd3-tip'
# d3.tip is defined with the following call
d3tip_module(d3)
d3.tip().attr('class', 'd3-tip')...

**Comment by darrenatyurgosky** [comment]
Same problem, thanks for the solution

**Comment by pdechery** [comment]
I was having the same problem and that worked. Thanks a lot for sharing.

**Comment by Caged** [comment]
I don't use commonjs, so if someone wants to submit a documentation update for this I'd be happy to accept it.
