### ISSUE TITLE
Will this work with d3 3.5.5 ?

### ISSUE THREAD

**Issue by RusAlex** [Caged/d3-tip#106]
Recent version of d3.js 3.5.5

**Comment by ddoolin** [comment]
I'm currently using it with 3.5.5, so yes.

**Comment by charlieartist** [comment]
Same here--and I'll also add that the latest version offers better RWD support now.

**Comment by Caged** [comment]
Released a version earlier today with support for 3.5.5.  https://github.com/Caged/d3-tip/releases/tag/v0.6.7
