### ISSUE TITLE
tip appending to a group

### ISSUE THREAD

**Issue by mawo87** [Caged/d3-tip#107]
I have a stacked bar chart. Each stack consists of two rectangles.
Now I've appended the tip to the groups instead of the rectangles. When I hover over the group the tooltip is not positioned on top of each group as expected. Instead it will be placed on top of each bar instead (see screenshot)
![bildschirmfoto 2015-04-07 um 11 53 27](https://cloud.githubusercontent.com/assets/1770915/7020866/c2342504-dd1c-11e4-8f12-e14dac9ec76b.png)

It is only placed correctly when hovering over the top of the two rectangles.
![bildschirmfoto 2015-04-07 um 11 55 04](https://cloud.githubusercontent.com/assets/1770915/7020896/f74bfba4-dd1c-11e4-9ff7-3edc02cac78e.png)

Even using the .offset callback did not solve the problem. I assume this behavior is caused due to the bbox?

**Comment by Caged** [comment]
Very late reply incoming... Difficult to know without an example but this is likely because each section of the bar is an individual element and you are binding to them individually.
