### ISSUE TITLE
Tip offset shifts in Safari

### ISSUE THREAD

**Issue by charlieartist** [Caged/d3-tip#111]
I've upgraded to the latest of d3-tip and Safari (8.0.6), and when mousing over RWD D3 visualizations in Safari, the tooltip is shifting, depending upon location. All is fine in Chrome and Firefox,though.

To be sure there wasn't some math being added, I tried it both with these settings:
.offset([-10,0])
.offset([0,0])

**Comment by jstvnn** [comment]
Is your zoom mode 100% or something else? This could be the same issue as https://github.com/Caged/d3-tip/issues/115

**Comment by Caged** [comment]
Triaging issues.  If this is still an issue could you please provide a working example?
