### ISSUE TITLE
Inline Style position always goes to 'absolute'

### ISSUE THREAD

**Issue by YomeKatsuma** [Caged/d3-tip#112]
I'am using d3-tip with **semantic-UI**.

After displaying a **semantic-UI Modal** the d3-tip is not well placed.

I've found this : 

Changing in the *initNode* function the **inline position style to 'fixed'**.
But, after showing/hidding and re-showing the d3-tip the **inline position style goes (and always stay) to 'absolute'**.

The only work arround is to use the **'!important'** keyword in the *css definition* : 

.d3-tip {
  position       : fixed !important;
 ...
}

I do not what happent here.

Cheer

Yome.

**Comment by YomeKatsuma** [comment]
Looks like this iisue : 

https://github.com/Caged/d3-tip/issues/102

**Comment by Caged** [comment]
Triaging issues.  Closing as likely duplicate.
