### ISSUE TITLE
Page zooming misplaces the tip in IE

### ISSUE THREAD

**Issue by jstvnn** [Caged/d3-tip#115]
Zooming the page enough in or out misplaces the tooltip in Internet Explorer 10. Zooming in Chrome and Firefox seems to work well though. 

This can be seen in the bar chart demo:
http://bl.ocks.org/Caged/6476579

**Comment by designfrontier** [comment]
Seeing the same thing for what it's worth

**Comment by Caged** [comment]
Triaging Issues.  Microsoft has dropped support for IE 10. http://venturebeat.com/2016/01/12/microsoft-ends-support-for-ie8-ie9-ie10-and-windows-8/
