### ISSUE TITLE
Wide tips (without explcit width) near the edge of the page aren't positioned correctly

### ISSUE THREAD

**Issue by tlrobinson** [Caged/d3-tip#117]
A wide tip placed near the edge of the page is sometimes offset from its correct position.

Setting a width in CSS seems to resolve this, but it would be nice if flexible sized tips worked.

**Comment by Lozzi** [comment]
I fixed my offset problem on the right/left side of the page by changing the `direction_n` function

```JS
   function direction_n() {
      var bbox = getScreenBBox()
      // check if the tooltip will go overflow right side of the page
      var screenRect = document.body.getBoundingClientRect()
      if (bbox.n.x + node.offsetWidth/2 > screenRect.width) {
          diff = ( bbox.n.x + node.offsetWidth/2 ) - screenRect.width
          return {
            top:  bbox.n.y - node.offsetHeight,
            left: bbox.n.x - node.offsetWidth / 2 - diff
          }
      }
      // check if the tooltip will go overflow left side of the page
      if (bbox.n.x - node.offsetWidth/2 < 0) {
          diff = node.offsetWidth/2 - bbox.n.x
          return {
            top:  bbox.n.y - node.offsetHeight,
            left: bbox.n.x - node.offsetWidth / 2 + diff
          }
      }
      return {
        top:  bbox.n.y - node.offsetHeight,
        left: bbox.n.x - node.offsetWidth / 2
      }
    }
```

**Comment by speedymcs** [comment]
You're a saint, @Lozzi! works very well for me.

**Comment by Lozzi** [comment]
@speedymcs Thank you! That's because I added the little triangle as a span in the nodes children to be able to do the calculations there.

```
tip.show = function() {
      var args = Array.prototype.slice.call(arguments)
      if(args[args.length - 1] instanceof SVGElement) target = args.pop()

      var content = html.apply(this, args),
          poffset = offset.apply(this, args),
          dir     = direction.apply(this, args),
          nodel   = getNodeEl(),
          i       = directions.length,
          coords,
          scrollTop  = document.documentElement.scrollTop || document.body.scrollTop,
          scrollLeft = document.documentElement.scrollLeft || document.body.scrollLeft
      // The span is the triangle
      nodel.html(content + '<span class="d3-tip__pin"></span>')
        .style({ opacity: 1, 'pointer-events': 'all', display: 'block' })

      while(i--) nodel.classed(directions[i], false)
      coords = direction_callbacks.get(dir).apply(this)
      nodel.classed(dir, true).style({
        top: (coords.top +  poffset[0]) + scrollTop + 'px',
        left: (coords.left + poffset[1]) + scrollLeft + 'px'
      })

      return tip
    }
```
And also changed it from `opacity: 1` to `display: 'block'` and  `opacity: 0` to `display: 'none'` since if you open a tip and resize your window it will overflow. Hope this helps :)

**Comment by speedymcs** [comment]
Ok I'm fairly new to web stuff.. where exactly do you add the triangle now? Somewhere in your css file?

**Comment by Lozzi** [comment]
```Javascript
nodel.html(content + '<span class="d3-tip__pin"></span>')
        .style({ opacity: 1, 'pointer-events': 'all', display: 'block' })
```
It's done there, in the `node.html()` in `tip.show = function ()`.
Then this is the CSS I'm using for it:
```CSS
d3-tip__pin {
  position: absolute;
  bottom: -9px;
  left: 50%;
  display: inline-block;
  width: 0;
  height: 0;
  margin: -11.5px;
  margin-bottom: -1px;
  box-sizing: border-box;
  border: 0 solid transparent;
  border-width: 11px 14px;
  border-top-color: #fff;
  border-bottom-width: 0;
  z-index: 1000000;
}
```
So by default the `left` of the triangle is 50% but gets overwritten in the element style if the `d3-tip` would go out of bounds: `node.children[node.children.length - 1].style.left = (node.offsetWidth / 2 + diff)` in the `function direction_n()`

Hope this helps :+1:

**Comment by speedymcs** [comment]
Thanks for the reply! So I've copied your updated `function direction_n()` as well as the `tip.show = function()` and added the CSS code. Bbut there's still no triangle.. I don't see the actual triangle symbol anywhere in the code either, I mean the original CSS for the tooltip contained this line: `content: "\25BC";`. I've tried adding it like this: `nodel.html(content + '<span class="d3-tip__pin">\u25BC</span>')` but that makes the triangle appear in the tooltip.
Maybe you have an idea what could be missing on my side?

**Comment by Lozzi** [comment]
The arrow pointing down is drawn with the border of the span. By having `borer-width: 11px 14px;` and putting the bottom width to 0 so that i makes a triangle, you shouldn't need any `content` in the span. Here's a little fiddle.
https://jsfiddle.net/xptup3uc/2/

**Comment by speedymcs** [comment]
Ok. After comparing every value in the fiddle with my code and more clueless debugging, I finally noticed that my CSS class was missing the dot in front. I'm hanging my head in shame. However it was your fiddle that made me notice and you gave me and hopefully others in the future insight into code.. thank you so much! It really should be added to the repository!

**Comment by Lozzi** [comment]
Glad I could help! :+1:

**Comment by Caged** [comment]
Triaging issues.  Thanks for the report!  This is a known issue and should be addressed as part of https://github.com/Caged/d3-tip/issues/8
