### ISSUE TITLE
Multiple Tip elements on UI

### ISSUE THREAD

**Issue by amit-rana** [Caged/d3-tip#118]
I have my dashboard page with full of d3.js bar and line diagrams .. and their code are build like model widget . all the bar chart's are stetting d3tip individuality in DOM . so when i change across multiple page on each time i come to dashboard it will add new 19 tip element to DOM ( site is simple page app with angularjs so it don't reload page just update inner view  ) and after sometime these tip elements start holding space sin dome and on ui performance get down.. any idea ?
for me there should be two possible solutions 
1) rather than adding element to DOM we can target them in to some division which we can reload .( i.e. one particular view or currently in view only )
2) or we should have global object which can handle multiple tips 

i tried to remove all d3tip before load view but it start giving errors

**Comment by breakingco** [comment]
same problem here.

**Comment by Caged** [comment]
Triaging issues.  If this is still an issue could you please provide a working example?

**Comment by brokenalarms** [comment]
I was using this for work so after a couple of days needed to move forward and wrote my own library for it. Glad I didn't wait for an answer ;) as far as I know the problem wasn't resolved.  I had to manually find and delete the tips by class in the DOM whenever I switched modules/views or they'd just keep multiplying. `.remove` didn't work. Hope that helps.
