### ISSUE TITLE
Not able to create SVG element in IE8 browser.

### ISSUE THREAD

**Issue by rsjeyakumar** [Caged/d3-tip#119]
I am using r2d3 library to make d3 chart  work in IE8 browser. 

In r2d3 library they are using 'shape ' element  instead of 'SVG' element.

My concern is d3-tip is not able to understand shape element. so it is throwing error  like 'not able to create SVG element'.

**Comment by Caged** [comment]
Triaging Issues.  IE8 is no longer supported.
