### ISSUE TITLE
Tip doesn't work with responsive SVG's 

### ISSUE THREAD

**Issue by d3QUone** [Caged/d3-tip#122]
E.g http://jsfiddle.net/BTfmH/12/

Any suggestion how to bring this to work?

**Comment by d3QUone** [comment]
I guess this is because of absolute positioning

**Comment by Samuel1989** [comment]
I am also suffering from this issue... Does anyone have a work around?

**Comment by Caged** [comment]
Triaging issues.  If this is still an issue could you please provide a working example?  The example above appears to be unrelated.
