### ISSUE TITLE
destroy method missing on npm 0.6.7.

### ISSUE THREAD

**Issue by acthp** [Caged/d3-tip#129]
In the repo v. 0.6.7 has a destroy() method, however when installing 0.6.7 from npm, there is no destroy method. Perhaps the npm publish was wrong?

**Comment by daver208** [comment]
Also having this issue.  The code on github does have a destroy() method for v0.6.7, but v0.6.7 installed from npm does not have the function.   Using `d3.select(".d3-tip").remove();` instead as a work-around.

**Comment by c-dante** [comment]
Also having this issue -- the package json is correct but the index.js from npm is old.

**Comment by joeandaverde** [comment]
+1

**Comment by vdh** [comment]
0.7.1 is now published, it should have the `destroy()` method
