### ISSUE TITLE
Calling d3.remove() doesn't remove old tool tips?

### ISSUE THREAD

**Issue by rohan-deshpande** [Caged/d3-tip#133]
Okay just to preface this, I am using d3-tip in a custom implementation of the d3 aster plot chart (https://github.com/bbest/ohi-aster) and React Js. I have created a legend from my data set and set it up so that when you mouse over the legend items, the applicable path's mouse event functions are called. 

It all works fine, however, when I need to destroy the chart and rebuild it, my tips (when called from the legend) are not getting cleared. I'm not entirely sure how this is possible, because I am passing the exact same tip reference to my legend as I am using when I build the chart. Anyway here is some relevant code:

```
//Aster Plot Chart component
handleMouseOver:function(tip, d, node) {
    tip.show(d, node);
    $(node).attr('style', 'fill:' + d.data.highlight);
},
handleMouseOut:function(tip, d, node) {
    tip.hide(d, node);
    $(node).attr('style', 'fill:' + d.data.color);
},
draw:function() {
    if(d3.select("svg")) {
        d3.select("svg").remove();
    }

    var tip =
        d3.tip()
        .attr('class', 'd3-tip')
        .offset([0, 0])
        .html(function(d) {
            return d.data.label + ": <span class='user-score'>" + d.data.score + "%</span>";
        });

    svg.call(tip);

    var path =
        svg.selectAll(".solidArc")
        .data(pie(this.props.data))
        .enter().append("path")
        .attr("class", "solidArc")
        .attr("stroke", "#ddd")
        .attr("d", arc)
        .on('mouseover', function(d) {
            self.handleMouseOver(tip, d, this);
        })
        .on('mouseout', function(d) {
            self.handleMouseOut(tip, d, this);
        });

    this.refs.legend.addEvents(d3, tip);
}

//Aster Plot Legend component
addEvents:function(d3, tip) {
    var self = this;
    var $items = $(React.findDOMNode(this.refs.legend)).find('li');
    var selection = d3.selectAll('.solidArc');
    var chartData = selection.data();
    var $item;

    $items.each(function(index, item) {
        $item = $(item);

        $item.on('mouseover', function() {
            self.props.parent.handleMouseOver(tip, chartData[index], selection[0][index])
        });
        $item.on('mouseout', function() {
            self.props.parent.handleMouseOut(tip, chartData[index], selection[0][index])
        });
    });
},
```

When I build the initial chart, everything works fine

![screen shot 2015-10-05 at 5 26 30 pm](https://cloud.githubusercontent.com/assets/1079637/10274166/686246ac-6b86-11e5-996f-4563956828a5.png)

However if any of my data changes, when the chart is rendered again and I mouse over the legend, there's now two tips:

![screen shot 2015-10-05 at 5 27 15 pm](https://cloud.githubusercontent.com/assets/1079637/10274173/7d42df1e-6b86-11e5-8bba-9f6195fe1a45.png)

This doesn't happen if I mouse over the actual nodes/paths, only over the legend, so this very well could be something wrong on my end. I thought it was curious though, because I would assume that calling d3's `destroy()` method would also remove all the tooltips...maybe it is and somehow through what I am doing I am creating other tooltips somewhere?

I'm wondering where the actual tips "are". Is there some way of accessing all the tips on a d3 object?

**Comment by LeeU1911** [comment]
I use the below to remove my d3-tip 
`d3.select(".d3-tip").remove();`
Note: d3-tip is the class of the tip html element in my case. I have only 1 tip so it can be different in your case.

**Comment by Caged** [comment]
Triaging Issues.  @LeeU1911's suggestion should work.  This doesn't appear to be a bug, but could you please provide a minimal example if you believe it is.  Thanks!
