### ISSUE TITLE
Root causes error in tooltip

### ISSUE THREAD

**Issue by ebremner17** [Caged/d3-tip#138]
so "checking functionality" in d3 tip actually causes errors in global scope in drupal.  

if (typeof define === 'function' && define.amd) {
     // AMD. Register as an anonymous module with d3 as a dependency.
     define(['d3'], factory)
   ...
     // Browser global.
     root.d3.tip = factory(root.d3)
   }

Removed all these lines and it worked in drupal.

**Comment by Caged** [comment]
Triaging issues.  If this is still an issue could you please provide a working example?
