### ISSUE TITLE
Keep mouseover Open While Mouse is Over Tooltip

### ISSUE THREAD

**Issue by realph** [Caged/d3-tip#151]
Is there an easy way to keep the tooltips open for a brief period of time?

I have a link in my tooltip that can be clicked and the tooltip closes once I hover off the node, meaning I can never hover over the tooltip.

Any ideas if this is possible?

Thanks in advance!

**Comment by khaledosman** [comment]
Having the same issue, it doesn't seem to be possible at the moment.. it tries to get the Bbox from the event.target 

var targetel   = target || d3.event.target; .. 

using jquery to manually trigger a mouseover event didn't work either... it seems that it only supports showing one tooltip at a time, if I comment out my mouseout handler, mousing over another element will hide the previous one's tooltip and only show the new one..

**Comment by Caged** [comment]
You can use `tip.show` during the click event instead of `mouseover`.   You might also try the example proposed here https://github.com/Caged/d3-tip/issues/103#issuecomment-96110423
