### ISSUE TITLE
is this project being maintained?

### ISSUE THREAD

**Issue by simoneb** [Caged/d3-tip#154]
Hello @Caged, this project is really useful but it seems that no one is taking care of it. Pull requests have been there for months and the there are no recent releases.

Would you please either let someone take over or perhaps pick one of the 222 forks as the new main development line?

**Comment by caleb272** [comment]
Hey simoneb, I'm new to d3 and want to use this library, are there any forks that work with V4 that you found.

**Comment by simoneb** [comment]
Haven't searched, you'll have to dig it out yourself probably.

**Comment by caleb272** [comment]
Yea i did here is the project https://github.com/VACLab/d3-tip

**Comment by simoneb** [comment]
awesome @caleb272, thanks for posting your findings!

**Comment by vdh** [comment]
D3 v4 support is now out with 0.7.1, any further PRs to improve d3-tip are welcome ;)
