### ISSUE TITLE
Does not work with D3 V4 Alpha

### ISSUE THREAD

**Issue by akuji1993** [Caged/d3-tip#155]
Hi, 

it seems like your (otherwise excellent) extension doesn't work with D3 version 4 (which is currently still in Alpha, so there's that). Please check if your extension still works, when D3 v4.0.0 comes out. 

Greetings.

**Comment by Restuta** [comment]
4.0.0.0 is there and it doesn't work for me as well.

**Comment by hkelly93** [comment]
It looks like @cgav forked it and made it work with v4

https://github.com/cgav/d3-tip

**Comment by cgav** [comment]
@hkelly93 It is still very experimental, but works so far in my use case.

**Comment by akuji1993** [comment]
Alright, thanks. Maybe include some note in your Readme, so people are aware about the issue with version 4. This issue can be closed, I guess.
