### ISSUE TITLE
Update to d3 v4

### ISSUE THREAD

**Issue by vdh** [Caged/d3-tip#156]
~~[d3](https://www.npmjs.com/package/d3) v4 was released [a couple of weeks ago](https://github.com/d3/d3/releases/tag/v4.0.0), and just recently published [v4.1.1](https://github.com/d3/d3/releases/tag/v4.1.1).~~
[d3](https://www.npmjs.com/package/d3) v4 was released [near the end of June](https://github.com/d3/d3/releases/tag/v4.0.0), and published [v4.2.1](https://github.com/d3/d3/releases/tag/v4.2.1) near the start of August.

~~As a (potential) starting point, it was mentioned in #155 that there's been some work already to support v4 in @cgav's fork: [cgav/d3-tip](https://github.com/cgav/d3-tip).~~ Sorry, I looked into it further, that fork isn't in a state that can be merged.

It would also be great to add d3 as a ~~[`peerDependencies`](https://nodejs.org/en/blog/npm/peer-dependencies/)~~ `dependencies` config in the package.json, so that the plugin's supported version range of d3 is more explicit.

**Comment by davegotz** [comment]
While the fork from @cgav supports d3 v4, it uses some new JavaScript features that didn't work in my environment.  I've shared my version of d3-tip, inspired by the work from @cgav, but with minimal changes to the older version so that it is more easily deployed.

It can be found here: https://github.com/VACLab/d3-tip

**Comment by vdh** [comment]
@davegotz Have you considered switching to an ES6 environment via Babel (compiling down to ES5)? It really is most sublime to be able to write with those newer features.

**Comment by vdh** [comment]
Paging @Caged, what's the status of d3-tip?

**Comment by Caged** [comment]
I simply haven't had the time or energy to pick this back up and also haven't used d3 in a while.  I hope that changes, I don't want to abandon the project, but in the meantime it looks like folks are carrying forward with fixes that get this working for d3 v4.

**Comment by micahstubbs** [comment]
can verify that @davegotz fork https://github.com/VACLab/d3-tip works well with **d3v4** in a script-tag or browser environment

**Comment by vdh** [comment]
I applaud the efforts of @davegotz and @cgav to improve d3-tip, but they both removed the AMD/CommonJS/browser switch in the header, which allows the library to work in multiple environments. They also both diverged master instead of forking, branching, and making a PR (or in @davegotz's case, started a completely different repo). So it's not possible to merge their changes back into the main repo.

I haven't worked with d3 much, but if someone could point out the relevant updates that needs to be updated for d3 `^4` compatability (hopefully, in a way that still works in `^3.5.5`), I could make a PR. I tried looking at the diff between davegotz/cgav's changes but I'm no d3 expert. Or if anyone else with more d3 chops than I feels like forking and making a PR I'll be happy to give a hand.

**Comment by vdh** [comment]
@Caged @davegotz @cgav @micahstubbs This new #158 PR from @besson-genostar looks promising, since it doesn't remove the AMD/CommonJS/globals code. Would anyone be interested in testing out that one?

I also made PR #159 extending his code with `peerDependencies` and d3 micro library dependencies instead of the whole d3, since that looks to be the direction that d3 wants to be heading with their code. I haven't had time to properly test it out though (I've hit a roadblock trying to convert some unrelated code to support v4's `d3-hierarchy`).

**Comment by vdh** [comment]
If #160 gets merged (update package.json to match bower.json) and 0.7.0 is released to npm, this issue should be ready to close, I think?

**Comment by Caged** [comment]
@vdh Thanks for pulling all of this together and making a little easier for me to sort through these PRs.  With that in mind, I've granted you push access to the repository.  It's up to you, but if you want to continue to work on d3 v4 support, you now have the means and I would absolutely encourage it 🌟 !  

As I mentioned, I hope to get back to this, but in the meantime this project could use a good shepherd and I would love to bring someone in to help with future releases so I'm not the single point of failure.   My email is in my profile if you want to get in touch outside of this forum.

**Comment by vdh** [comment]
@Caged Wow thanks! I think I'll need to get more familiar with d3 (especially v4) before I can be a proper shepherd of this project, but I'll certainly try to help out with PRs and such from contributers 😄

**Comment by vdh** [comment]
@Caged So will you still be handling the NPM releases?

**Comment by glebmachine** [comment]
+

**Comment by Caged** [comment]
@vdh Just returning from vacation and reading your message.  yeah, you can publish new releases on npm.  I might need to flip some switches to give you access.  Let me know what you need.  Thanks!

**Comment by vdh** [comment]
@Caged You could add me using the [`npm owner`](https://docs.npmjs.com/cli/owner) cli command. Surprisingly, Npm only uses that one level of access.

**Comment by Caged** [comment]
@vdh It turns out I didn't originally publish d3-tip to the npm registry, so I don't own the package.  I've emailed the current owner [per this doc](https://docs.npmjs.com/misc/disputes).  Hopefully we'll hear something back soon, otherwise we might have to choose a different name 😞

**Comment by micahstubbs** [comment]
@Caged fascinating.  thanks for sharing the backstory.

**Comment by vdh** [comment]
@Caged Ahh! That explains that earlier issue of the last release of d3-tip not being deployed correctly on npm. Well, hopefully we can get that package ownership fixed up

**Comment by Caged** [comment]
@vdh what is your npm name?

**Comment by vdh** [comment]
@Caged Same as here, `vdh`

**Comment by Caged** [comment]
@vdh you're now an owner of the npm package!  You should be good to go on publishing 0.7.0.

**Comment by vdh** [comment]
NPM was fussy about 0.7.0 being occupied by something, so I had to publish 0.7.1 instead. But hey, we have d3 v4 now! 😄

**Comment by baerrach** [comment]
Pulled 0.7.1 from npm fine. Working as advertised.

Thanks for this! I was just looking at using d3-tip with D3 v4 over the last few days so this was a timely fix.

**Comment by vdh** [comment]
@baerrach Also, if you need a version that makes use of d3's new micro libraries instead of the whole library, I've got a branch in the works for that. It'll probably be `0.8.0` in case anyone wants to keep using just `d3` with `0.7.x`

**Comment by baerrach** [comment]
Do you have links to micro libraries?
I'm using rollup and tree-shaking, but I've not confirmed that shrinks everything for me. I just know stuff works.

**Comment by vdh** [comment]
@baerrach Here's where it's mentioned: https://github.com/d3/d3/blob/master/CHANGES.md

If you're using tree-shaking that might already reduce the output size for you already, depending on if the optimisation can successfully identify and strip the unused d3 micro libraries.

In a nutshell, `d3` v4 is now just a thin wrapper around the micro libraries. Switching to micro libraries just means `require`ing/bunding those dependencies à la carte instead of via the `d3` wrapper.

I have a (very temporary) branch of it here while we get the linting and other maintenance stuff set up first: https://github.com/vdh/micro-libraries (for a slightly-less-temporary branch use https://github.com/vdh/v0.7.1-temp-fork )

**Comment by baerrach** [comment]
Oh right, I am definitely using modules.

As I'm new to ES6 and the d3 documentation for v4 doesn't go into enough detail when using modules (and things like rollup) it took me a while to work stuff out.

As all the documentation assumes you are importing all of d3 into the `d3` namespace, when you move to modules you either have to drop the d3 prefix, or work out how to import a bunch of modules into the d3 namespace. Finally I worked out you need to [create your own local d3 module where you import/export the bits that you want.](http://stackoverflow.com/questions/38637220/how-to-include-use-of-node-modules-in-rollup-compile/38653264#38653264)

d3-tip will need to include similar documentation.

**Comment by vdh** [comment]
Whoops, I got those branch links messed up in my previous comment.

@baerrach You actually only need to roll your own `d3` namespace when you're not using a module loader (i.e. when you're using it raw, directly in the browser).

If you're using a module loader (compatible with AMD or CommonJS), you can just `require` the modules directly. Check out this comparison to see how little the current `d3-tip` needed to be changed to use micro libraries: https://github.com/Caged/d3-tip/compare/linting...vdh:micro-libraries

You don't need a `d3` variable any more, you can just use the methods defined inside the namespaces you get when you `require` the micro libraries directly:
```js
// instead of:
var d3 = require('d3')
var div = d3.select(document.createElement('div'))
// you can now just do this:
var d3Selection = require('d3-selection')
var div = d3Selection.select(document.createElement('div'))
// or if you're using ES6:
import d3Selection from 'd3-selection'
const div = d3Selection.select(document.createElement('div'))
```

**Comment by baerrach** [comment]
Sure, but then all the existing cut-n-paste examples need reworking :)
I found it easier to roll my own d3 namespace.

**Comment by vdh** [comment]
@baerrach Compatibility with cutting and paste large swaths of code doesn't sound like the best coding strategy 😦 

You're also reducing your performance by requiring dependencies where they're not needed, and adding a new build dependency for the rollup, just to remove the need to rename a few variable references? It seems weird. _Every_ module is already in their own namespace, you don't need to double-namespace them to make outdated code examples happy.
