### ISSUE TITLE
d3-tip in Typescript

### ISSUE THREAD

**Issue by dekonunes** [Caged/d3-tip#163]
There is this code in Typescript?

I'm programming in Angular 2 and this chart will help so much.

Thank you.

**Comment by vdh** [comment]
As far as I'm aware about how TypeScript works, you can still use external JS libraries with your TS code. What's stopping you from importing d3-tip?

**Comment by dekonunes** [comment]
First was looking for TS, but don't find a good code of D3 in TS. Will try use JS.

Thank you.
