### ISSUE TITLE
Button Inside tooltip

### ISSUE THREAD

**Issue by bliitzkrieg** [Caged/d3-tip#167]
Is there a simple way through the API to have a button inside the tooltip that is clickable?

**Comment by Caged** [comment]
Hi @bliitzkrieg.  This sounds like a general question better suited for StackOverflow.  We'd like to keep the issue track as a place to report, discuss, and prioritize bugs.   

You should be able to put HTML in the tip using something like: `tip.html("<button>Foo</button>")`
