### ISSUE TITLE
Uncaught TypeError: (intermediate value)(...) is not a function

### ISSUE THREAD

**Issue by jdcast** [Caged/d3-tip#169]
Note: running meteor 1.4.1.1

I tried placing index.js under `client/compatibility` (per https://guide.meteor.com/structure.html) so as to be able to use d3-tip as an external js library.  
I downloaded the code base from release (https://github.com/Caged/d3-tip/releases/tag/v0.6.7) (tar.gz) and received the error (in js console) in the heading of this question after placing index.js under `client/compatibilty`.  I was able to fix by placing a semi-colon at start of line 6 in index.js.

**Comment by Caged** [comment]
Can you please provide an isolated example that we can use to reproduce this?  You might try updating or testing the library without meteor included on the page.
