### ISSUE TITLE
d3 tip in sunburst

### ISSUE THREAD

**Issue by c-arnab** [Caged/d3-tip#172]
I added d3 tip to sunburst chart ( http://bl.ocks.org/mbostock/4348373), though the tip shows its position is completely wrong. I tried changing the offset values in d3.tip command but could not get it right.
I have created a jsfiddle of the code I used: http://fiddle.jshell.net/72uju5kp/1/

Though in my application almost all the tip's position is wrong.. in the above fiddle the problem can be viewed primarily in the top right quadrant for vis, operator and layout

**Comment by Caged** [comment]
Thanks for providing the demo.  It looks like the positions are correct to me and we're still missing key information to help diagnose the problem.  

* What browser version and OS are you using?
* If it's Chrome on OSX, what results are you expecting? 

Keep in mind that the position is based on a bounding box rectangle, so arcs might be a little troublesome in this case. Someone has a put together a better version for [arcs](https://github.com/Caged/d3-tip/pull/54/files).
