### ISSUE TITLE
rootElement.appendChild is not a function

### ISSUE THREAD

**Issue by niamleeson** [Caged/d3-tip#177]
even if you pass `document.body` to `.rootElement()` function, this error is returned.

```
rootElement.appendChild is not a function
```

**Comment by Caged** [comment]
Can you please provide a working sample replicating the error?

**Comment by vdh** [comment]
It's because of the incorrect use of `functor` in the `rootElement` code. It would be fixed by #175 but that hasn't been merged yet due to issues with the scroll code logic.
