### ISSUE TITLE
RootElement option is a function when calling `appendChild`

### ISSUE THREAD

**Issue by Gbuomprisco** [Caged/d3-tip#180]
Hi,

I am trying to use the `rootElement` option, but the problem is that this gets transformed to an anonymous function, and therefore when `appendChild` gets called, an error is returned instead. I am using just by passing the DOM element to the method (and as shown in the examples), so I suppose I am not doing something wrong. 

Happy to submit a PR if it helps, thanks!

**Comment by Gbuomprisco** [comment]
Sorry, I just had a look at https://github.com/Caged/d3-tip/pull/175/files, this will probably fix the issue.

**Comment by vdh** [comment]
@Gbuomprisco There's still some issues that need to be resolved in that PR, if you have any advice about it that could help out a lot
