### ISSUE TITLE
Does the tooltip work with divs, created through html?

### ISSUE THREAD

**Issue by Stophface** [Caged/d3-tip#182]
I want to use the tooltip in a slightly different manner!
I select a `div` with `d3.select`. That `div` is not created through `d3`, but static html. Therefore, there is no `d3.data().enter().append()...` involved in creating it.
I then want to attach a tooltip to that `div` .
However, that throws me:

> Uncaught TypeError: Cannot read property 'createSVGPoint' of undefined(…) 
> d3.tip.v0.6.3.js:20

Thats how I try it:

    var tip= d3.tip().attr('class', 'd3-tip').html("This is a tooltip");
    var myDiv = d3.select("#someId");
    myDiv.call(tip);
    myDiv.on("mouseover", tip.show);
    myDiv.on("mouseout", tip.hide);

**Comment by Caged** [comment]
d3-tip only works with SVG.  There are some [pure css](https://codepen.io/cristina-silva/pen/XXOpga) tooltip examples that are likely better suited for HTML elements.
