### ISSUE TITLE
Tooltip doesn't show in fullscreen

### ISSUE THREAD

**Issue by jessmitch42** [Caged/d3-tip#184]
Hi there,

This tool-tip has been very helpful for a project I'm working on; however, the tool-tip doesn't show up on hover (or at all) when in full screen. I haven't been able to get it to work and I noticed that in the example it doesn't show up unless the bar is clicked. http://bl.ocks.org/Caged/6476579

Any ideas on how to get it to function the same in full screen?

Thanks in advance!

**Comment by Caged** [comment]
Hi @jessmitch42,

Ohh, interesting.  I was able to reproduce this in Chrome.  It works fine in Safari. Thanks for the report.
