### ISSUE TITLE
Possible to use d3.tip and another action on mouseover/mouseout?

### ISSUE THREAD

**Issue by 1django** [Caged/d3-tip#185]
Is it possible, on mouseover/mouseout of an element, to trigger both the tooltip function and another action (say modify the radius of the circle the tooltip is on)?

Thanks.

**Comment by jessmitch42** [comment]
ya, you just have to call the tool tip slightly differently than the basic example. 

`.on('mouseover', function (d) {
          // whatever else you want to do, then:
          tip.show(d)
        })`

**Comment by 1django** [comment]
I figured there was a way...thanks!
