### ISSUE TITLE
always shown tip

### ISSUE THREAD

**Issue by eMerzh** [Caged/d3-tip#186]
is there a way to make the tip always shown and not dependant of an event or smth ?

Thanks :)

**Comment by marco-lobo-jd** [comment]
I'm also interested on this feature. @eMerzh Did you manage to do something on your own?

**Comment by eMerzh** [comment]
@marco-lobo-jd no, didn't get the time to explore it yet... never say never but if you find smth i'm interested ;-)

**Comment by Pehesi97** [comment]
I'm interested too. Did anyone find out anything on that?

**Comment by gordonwoodhull** [comment]
Shouldn't it work just to call `tip.show()` manually, instead of in response to an event? You're in complete control of when the tip is shown and hidden.
