### ISSUE TITLE
Uncaught TypeError: Cannot set property 'x' of null

### ISSUE THREAD

**Issue by tgelu** [Caged/d3-tip#187]
I am just trying to make a demo with the simplest example:

```
var tooltip = d3.tip()
                    .attr('class', 'bar-chart__tooltip');
...

bar.on('mouseover', tooltip.show);
```

I am literally doing nothing else but I am getting the error using latest version:
```
Uncaught TypeError: Cannot set property 'x' of null
at getScreenBBox ((index):574)
    at Function.directionNorth ((index):455)
    at Function.tip.show ((index):325)
```

**Comment by Caged** [comment]
Did you bind the tooltip to the vis according to [the demo](https://github.com/Caged/d3-tip#quick-usage)?   You need a `yourSVG.call(tooltip)` if you don't have it.

**Comment by tgelu** [comment]
Of course not, silly me.
Thank you!

**Comment by santosh-k1** [comment]
yes need to add `path.call(tip); after` .`on('mouseout', tip.hide);` the issue can resolve 
```
var path = svg.selectAll(".solidArc")
        .data(pie(data))
      .enter().append("path")
        .attr("fill", function (d) { return d.data.color; })
        .attr("class", "solidArc")
        .attr("stroke", "gray")
        .attr("d", arc)
        .on('mouseover', tip.show)
        .on('mouseout', tip.hide);
     path.call(tip);
```

**Comment by kimmiekim** [comment]
i did bind yourSVG.call(tooltip) but it's giving "Cannot read property 'toLowerCase' of undefined" error.. any  idea?
