### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by WebDevPDX** [Caged/d3-tip#189]
Hey, 

I am using d3-tip on some of my d3 charts (particularly on codepen) and I am pulling the tip in from http://labratrevenge.com/d3-tip/javascripts/d3.tip.v0.6.3.js. But lately I am getting a CORS error. Any chance that there is a secure link somewhere that I am just not aware of?

**Comment by Caged** [comment]
Please don't serve d3-tip from my personal website!   Serving it yourself or serving it from a service like https://rawgit.com would be better.  (P.S. the current version is 0.8 alpha)
