### ISSUE TITLE
rootElement sometimes variable sometimes function

### ISSUE THREAD

**Issue by scottp** [Caged/d3-tip#190]
The rootElement function call uses functor to set the rootElement variable to a function.

The rest of the code then tries to set rootElement.append or similar instead of rootElement().append. This inconsistency makes the library impossible to change the tip location from a body to div.

**Comment by vdh** [comment]
There's been some unresolved issues with rootElement ( See #175 ). I haven't been able to round up help to fix it, and I'm unfortunately not active enough to be able to fix it myself.
