### ISSUE TITLE
d3-tip  RootElement

### ISSUE THREAD

**Issue by jagrawat** [Caged/d3-tip#191]
when ever we pass a div in
**d3.tip().rootElement(--->div<---)**
the functor returns a function of that div such that it becomes impossible to append "node"(d3- tip div) .
even when we pass the default rootElement i.e. document.body
**d3.tip().rootElement(document.body)**

it is unable to append the "node"(d3-tip div)
this above throws error in return.

**Comment by Caged** [comment]
I'm not 100% sure I follow. Could you please link to a working example demonstrating the problem?

**Comment by vdh** [comment]
There's been some unresolved issues with `rootElement` ( See #175 ). I haven't been able to round up help to fix it, and I'm unfortunately not active enough to be able to fix it myself.

**Comment by jagrawat** [comment]
I believe this will help you understand the issue
https://gist.github.com/anonymous/a78994549d6b9487bb6c10cfc3d7289a

**Comment by jagrawat** [comment]
@vdh you changed the library which even i did. but i wish @Caged update the core d3-tip function.

**Comment by jagrawat** [comment]
@Caged have u checked the issue ?

**Comment by Caged** [comment]
I have not.  I haven't had time. Feel free to look into https://github.com/Caged/d3-tip/pull/175 or submit a PR if you have time.

**Comment by jagrawat** [comment]
@Caged i checked and its working but i want you to update the core library removing the bugs from library.

**Comment by mersadk** [comment]
I don't know if this is the best solution but it works. Update rootElement() definition to:
```
tip.rootElement = function (v) {
	if (!arguments.length) return rootElement
	rootElement = v;

	return tip
}
```

**Comment by jayeshx24** [comment]
hey @Caged  can i raise a pull request to solve this issue?

**Comment by strife-cloud** [comment]
Hello, I have the same issue and I really need this function for my web app or at least can you give me the patch to apply it so I can work with this function?
