### ISSUE TITLE
Should pointer-events ever be set to all?

### ISSUE THREAD

**Issue by Shians** [Caged/d3-tip#195]
I tracked down an issue in a downstream package [ubit2](http://pklab.med.harvard.edu/jean/ubit2/index.html) which exhibits major jittering issues with the tooltip. Try moving the mouse horizontally across the "Hierarchical Clustering Heatmap" at the bottom of the page to see what I'm talking about.

The issue is that the tooltip is usually place in front of underlying figures, and enabling pointer-events means that the tooltip absorbs the next mouse movement, causing a ```mouseout``` of the underlying figure and hiding the tooltip. This is not an issue in your demo code because the tooltips are placed entirely above the bars, but had they even slightly intersected the bars then this would have become an issue.

I would imagine it's quite common for people to place tooltips in a way that causes this jittering behaviour, and I don't see any particular benefit to allowing pointer-events on the tooltip itself. Could I recommend that you not have this be the default behaviour?

**Comment by baygeldin** [comment]
I've had the same problem and I fixed it by `pointer-events: none !important` in CSS. It isn't a pefrect solution (kind of a last resort), but it works and it doesn't require monkey pathing.

**Comment by davidlukerice** [comment]
I'm having a similar issue that needed the `pointer-events: none !important` to fix.
I have the tooltip following the mouse (via the https://github.com/Caged/d3-tip/issues/53 circle workaround) and if the update lags a bit the mouse often moves on top of the tooltip, emitting a 'mouseout' event for what the mouse was hovering over previously.
