### ISSUE TITLE
multi lines chart example

### ISSUE THREAD

**Issue by snowman55** [Caged/d3-tip#20]
Can you add an example for using tool tips to a multi-lines chart e.g.  http://bl.ocks.org/mbostock/3884955 
Thanks

**Comment by josiahdavis** [comment]
+1 

Having the ability to use them on the multi-series chart would be fantastic.

Thanks!

**Comment by Caged** [comment]
Closing as not a bug.  The example in the comment above should work and also [explicit targets](https://github.com/Caged/d3-tip/blob/master/docs/showing-and-hiding-tooltips.md#explicit-targets) are now part of the project.
