### ISSUE TITLE
Very useful. Are there any plans to update it to be compatible with D3 v4.x?

### ISSUE THREAD

**Issue by dgwyer** [Caged/d3-tip#204]

**Comment by Bengreen** [comment]
i am using with D3.v4 at moment and seems to be fine.
version : 0.8.0-alpha.1

**Comment by Wikunia** [comment]
It would be nice if this http://labratrevenge.com/d3-tip/javascripts/d3.tip.v0.6.3.js would be updated as well.
Nice to have a CDN version and not just npm and stuff like that ;)

**Comment by louking** [comment]
I'm able to download from https://cdnjs.cloudflare.com/ajax/libs/d3-tip/0.8.0-alpha.1/d3-tip.min.js
