### ISSUE TITLE
Issue with responsive svg. 

### ISSUE THREAD

**Issue by sreerajpjayaraj** [Caged/d3-tip#205]
I tried the "tip" for a bar chart based on the [example](http://bl.ocks.org/Caged/6476579)
It's working file for svg with fixed width and height. But the tip position have issues with the svg if it made responsive via attributes **viewBox** and **preserveAspectRatio**.

If the svg is scaled down from the width specified in viewBox the tip is positioned further top from it's initial  position. i.e. the distance between the tip and the chart increases as the chart's width is reduced.

if chart has viewBox = "0 0 500 300" then the chart drawn in a smart phone will have the "tip" positioned on top but it would be no where near the  chart.

**Comment by LukasV** [comment]
Hello there, I'm having same issue with the tips not responding (changing position) according to the parent SVG's dimensions. Any fix to this? Suggested solution? Idea at all? :)

**Comment by sreerajpjayaraj** [comment]
Hello Lukas, I didn't get a solution in D3. I wrote a CSS to position the tooltip in a fixed position for small screen devices.
