### ISSUE TITLE
Use peerDependency instead of a direct depencency on d3-*

### ISSUE THREAD

**Issue by VanTanev** [Caged/d3-tip#206]
Hello, 

Right now in [0.7.1 package.json](https://github.com/Caged/d3-tip/blob/v0.7.1/package.json) you have a direct dependency on `d3`, and in [current package.json](https://github.com/Caged/d3-tip/blob/0da986450e30413ffc1ae603a0bc813db5126f6e/package.json) you have direct dependencies on `d3-collection` and `d3-selection`.

These dependencies are used to access the globally available `d3.event` or `d3Selection.event` properties. However, with direct dependencies, your users WILL end up with different versions of those objects when using any webpack-like build system.

The reason is that you have `"d3": "^4.2"`, which resolves to the LATEST `4.X` version. If a user had `"d3": "~4.8.0"` in their `package.json`, this will result in 2 different versions being resolved, which means that `d3-tip` will get its own instance of `d3` at, say, version `4.10.0`, while the instance used by the the main app code will be `4.8.0`. 

The result is that `function getScreenBBox()` will explode with type error no property target of null, because in `d3-tip`'s instance, `d3.event` will be `null`.

This can be solved by defining `d3-tip`'s dependencies as `peerDependency`, and having it always use the version specified by the actual app `package.json`.

**Comment by VanTanev** [comment]
Read more about peer dependencies here: https://nodejs.org/en/blog/npm/peer-dependencies/

**Comment by wilkerlucio** [comment]
@VanTanev I'm getting bitten by this very issue, is there a specific d3 version that I can set to make it work?

**Comment by VanTanev** [comment]
@wilkerlucio Hey, in our case we're using:
```
```

**Comment by VanTanev** [comment]
@wilkerlucio Hey,
In our case we're using
```
"d3": "^4.2",
"d3-tip": "^0.7.1",
```

Basically, we're using the same string for our `d3` dep as what is specified in `d3-tip` here: https://github.com/Caged/d3-tip/blob/v0.7.1/package.json#L28

It's different for master, to keep that in mind. 

Again, this very much needs to be fixed here by changing `d3` to a `peerDependency` for `d3-tip`. Or, maybe a fork, if the maintainers here have no intention of fixing it.

**Comment by kylezeeuwen** [comment]
Here's a fork that specified D3 v3 as a peer dependency : https://github.com/Displayr/d3-tip/releases/tag/v1.3.0 . Note I didn't merge over top of master, I just created a new release tag "v1.3.0"

**Comment by khaledosman** [comment]
I have the same problem, in my case I'm working on an old project that's using d3 v3 with webpack and d3-tip installs and uses d3 v4 which doesn't work :/

**Comment by VanTanev** [comment]
@Caged This is still relevant, and not difficult to fix (but would probably require a point release instead of a patch release). Should I write a PR for it?
