### ISSUE TITLE
using rootElement

### ISSUE THREAD

**Issue by Bengreen** [Caged/d3-tip#208]
There seems to be something funny with using rootElement to set the root for the tooltip div.
This is a great feature as it lets me scope the tip inside my objects easier.

The problem is that when i provide the element to be inserted into it is not calling it through a function call when doing the appendChild
current code is:
`rootElement.appendChild(node)`
which complains as the assignment method assigns a functor.
So i think the code needs to be changed to
`rootElement().appendChild(node)` which works nicely. But breaks with the default assignment of `document.body`, which i assume now needs to be wrapped in a functor.

**Comment by vdh** [comment]
The `rootElement` feature has been problematic. It was included from a contributer and then nobody seemed to want to step forward to fix the issues a second contributer raised about it (see #175). I haven't really had any time spare to help out with it either.
