### ISSUE TITLE
Positioning tooltip according to mouse position

### ISSUE THREAD

**Issue by marioosh-net** [Caged/d3-tip#213]
Is a way to position tooltip that follows a mouse position ? Something like in this example: https://bl.ocks.org/mbostock/1087001

**Comment by Misterfluff** [comment]
I am unable to get my groupLabel to display in the tool tip. The subGroup Labels display with no problem. What am I missing? My file is attached. Thanks ever so much for any assistance.

[groupedHorizontal-1.html.zip](https://github.com/Caged/d3-tip/files/1789889/groupedHorizontal-1.html.zip)

**Comment by caged** [comment]
Closing as stale/not-a-bug.  Could you please use StackOverflow for general questions?  I'd like to keep the Issue tracker focused on bugs.
