### ISSUE TITLE
Webpack imported Module is not a function 

### ISSUE THREAD

**Issue by guitar9** [Caged/d3-tip#220]
i installed d3.tip() with 
npm install d3-tip

i get this error: 
Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_2_d3__.tip is not a function

My Versions: 
"d3": "^4.13.0",
"d3-tip": "^0.7.1",

**Comment by guitar9** [comment]
somebody has an idea?

**Comment by caged** [comment]
This should be fixed in 0.9.1.
