### ISSUE TITLE
Do you have any examples of how to set this up with Angular 2+?

### ISSUE THREAD

**Issue by johnsocf** [Caged/d3-tip#221]
Do we add it in ngModule as an import, and if so how would this best look and be referenced?  Also, can this be integrated with things such as d3-ng2-service?  My d3 service is a bit different since it's in angular 2, so it's not recognizing it I think as compatible out of the box.  Do I need to build something more custom?  Or can this be integrated.

**Comment by jplew** [comment]
I have the same use case and question. When I try this:

    const tip = d3.tip()

I get this:

    "export 'tip' (imported as 'd3') was not found in 'd3'

Did you ever find a workaround?

**Comment by jplew** [comment]
Never mind, I see there's a big discussion about it over here: https://github.com/Caged/d3-tip/issues/181

**Comment by jplew** [comment]
StackBlitz example: https://stackblitz.com/edit/d3-tip-angular-example?file=app%2Fd3-chart%2Fd3-chart.component.ts

Needs some work though.
