### ISSUE TITLE
can't detect that svg has moved

### ISSUE THREAD

**Issue by GopherJ** [Caged/d3-tip#224]
I've used `d3-tip` in vuejs to create some d3 component, It works well if I use these components individually,
but when I use it in `vue-grid-layout` which is a version of gridster in vuejs. The problem comes, every time when I move my `grid-item`, the `tool-tip` stay at the old position.

Any one can give me some help?

**Comment by caged** [comment]
Hi, could you please use stackoverflow for general questions.  If you could provide a demo of the problem it would be easier to look into.  My guess is that you need to listen for grid changes and reinitialize the tip.

**Comment by 0x8f701** [comment]
Hello Caged, sorry that I forgot to close this issue, I've solved my problem by using https://github.com/timoxley/offset to get the offset of the target, and use d3 to change tooltip's position. 

But I'am not sure where is the problem,  I guess It's multiple div of `position: absolute` make the tooltip get the false position.
