### ISSUE TITLE
TypeError: targetel.getScreenCTM is not a function

### ISSUE THREAD

**Issue by wschue** [Caged/d3-tip#231]
I'm getting a TypeError: targetel.getScreenCTM is not a function using latest code v0.9.1:

![image](https://user-images.githubusercontent.com/39309641/40069780-8c1f3dd6-586c-11e8-8f74-3eff12ad8626.png)

**Comment by jzlai** [comment]
Got the same problem

**Comment by gaetanlefrioux** [comment]
Got the same as well

**Comment by caged** [comment]
Can you provide more info and the smallest possible test example?  Browser, OS, etc.

**Comment by jonasius** [comment]
Same problem for me. But can't create a test example at the moment.
I tried to use it under:
Windows 7
Chrome 66
Angular v6.0
D3 v5.4
d3-tip v0.9.1

**Comment by inovux** [comment]
Hi guys, This problem is very easy to fix:

`
.on('mouseover', function(d) {
    tip.show(d, this);        
})
`

Make sure you pass your show or hide method a second argument of 'this'. So targetel will me defined with the current element you are hovering on.

**Comment by jzlai** [comment]
@inovux thanks, that worked

**Comment by jonasius** [comment]
@inovux thanks, it worked for me too!
Maybe as an additional note, it is important to use `function(d) { tip.show(d, this); }` NOT `(d)=>{ tip.show(d, this); }`
And only use `this` on mouseover, otherwise the tooltip won't hide on mouseout.

@jplew this should fix your issue/example https://github.com/Caged/d3-tip/issues/221#issuecomment-385282447

**Comment by wschue** [comment]
thanks, working as described.

**Comment by strife-cloud** [comment]
Someone should change the documentation : https://github.com/Caged/d3-tip/blob/master/docs/showing-and-hiding-tooltips.md#tipshow because it can be misleading

**Comment by MDiraz** [comment]
Another alternative that would work with arrow functions is:

`.on('mouseover', (d, i, n) => tip.show(d, n[i]))`

I running D3 v5.7.0 for reference.

**Comment by vijaykanta** [comment]
> Another alternative that would work with arrow functions is:
> 
> `.on('mouseover', (d, i, n) => tip.show(d, n[i]))`
> 
> I running D3 v5.7.0 for reference.

Yes, this is the most appropriate answer. Works like a charm!

**Comment by calindotgabriel** [comment]
does not work under preact with all the answers above, still getting the error :/
