### ISSUE TITLE
Positioning in Firefox

### ISSUE THREAD

**Issue by jzlai** [Caged/d3-tip#232]
Hey, so the Tooltip gets positioned weirdly in Firefox for me.
<img width="127" alt="bildschirmfoto 2018-05-23 um 12 57 29" src="https://user-images.githubusercontent.com/10701121/40420548-046840b8-5e89-11e8-8d12-aa156ee3b74c.png">

It's supposed to be directly above the point at the bottom. I have 2 divs there, nested in a react-grid-layout and I suppose it might have something to do with getScreenCTM which is different in Firefox from the other browsers.

See [https://stackoverflow.com/questions/37417075/svg-getscreenctm-for-nested-svg-is-different-in-firefox](here)

Any ideas?

**Comment by voyti** [comment]
Same issue for me

**Comment by oksanazaporozhets** [comment]
Issue is still reproducing
