### ISSUE TITLE
d3-tip does not work on tspan in Firefox

### ISSUE THREAD

**Issue by stof** [Caged/d3-tip#236]
due to https://bugzilla.mozilla.org/show_bug.cgi?id=937268, using d3-tip on a `tspan` triggers a `NS_ERROR_NOT_IMPLEMENTED` error in Firefix when calling `getBBox()`

**Comment by stof** [comment]
AFAICT, this issue is still valid.

**Comment by stof** [comment]
@Caged having a robot marking issues as stale and auto-closing them while none of them get attention from a maintainer look really weird to me btw.

**Comment by stof** [comment]
this issue is still valid

**Comment by Mounicasri123** [comment]
this issue is still valid

**Comment by stof** [comment]
@Mounicasri123 based on https://github.com/Caged/d3-tip/issues/239#issuecomment-443053926 this library seems unmaintained.
