### ISSUE TITLE
Any plans to update the library to d3 v5 ?

### ISSUE THREAD

**Issue by elChapoSing** [Caged/d3-tip#239]
For some other projects I do need to use d3 v5. It would be amazing to get the d3-tip library fully compatible. Unfortunately I wouldn't even know where to start.

**Comment by caged** [comment]
Hi @elChapoSing, I no longer actively use this library so I likely won't update it to v5.  Sorry for that.

**Comment by elChapoSing** [comment]
Ok no problem at all obviously 🙂
Any good replacement libraries you could point me to? Or will I have to
stick to native d3 (which would be painful)?
