### ISSUE TITLE
Adjust name of JavaScript file in dist folder.

### ISSUE THREAD

**Issue by SeppPenner** [Caged/d3-tip#244]
When I take a look at e.g. d3-array, there is a folder called `dist`: https://cdn.jsdelivr.net/npm/d3-array@2.0.3/dist/.

Could you provide your script also with a `dist` folder with `d3-tip.js` and `d3-tip.min.js`, please?

Having a `index.js` in the dist folder (https://cdn.jsdelivr.net/npm/d3-tip@0.9.1/dist/) is a bad idea because this name is quite commonly used and might cause errors when you try to bundle the script...

**Comment by stof** [comment]
why would it cause error when bundling ? Bundlers are able to deal with multiple files named `index.js` in different folders.

**Comment by SeppPenner** [comment]
I have a. ASP.Net Core project where you first define a package mapping which copies the files from the `node_modules` folder to a certain folder in the project strucutre using a `package-mapping-config.js` file. Therefore, it would be needed as multiple files could be copied to the same folder. Bundling itself is not the problem. (Thanks for the information by the way, my question was misleading, I guess).

**Comment by stof** [comment]
Well, I would consider that an issue of this project then. Enforcing unique file names among the whole npm ecosystem is not something that will ever happen IMO, especially if it is meant to satisfy the needs of a tool in a different ecosystem.

Anyway, according to https://github.com/Caged/d3-tip/issues/239#issuecomment-443053926 this package is not maintained anymore, so this is even less likely to happen.

**Comment by SeppPenner** [comment]
> Anyway, according to [#239 (comment)](https://github.com/Caged/d3-tip/issues/239#issuecomment-443053926) this package is not maintained anymore, so this is even less likely to happen.

Thanks for the update. I didn't know that. Ok, then I will use another implementation...
