### ISSUE TITLE
tip is not a function

### ISSUE THREAD

**Issue by garrettstevenkeyes** [Caged/d3-tip#245]
When I link to the index.js file with the tooltip in it I get this error:

Unexpected token {

and I also get:

d3.tip is not a function

How to i solve this so the tooltip is useable?

**Comment by Zveroboev** [comment]
@garrettstevenkeyes hi, do you have find a way to fix this ? I met the same question

**Comment by SeppPenner** [comment]
The library is no longer developed... https://github.com/Caged/d3-tip/issues/239#issuecomment-443053926.
