### ISSUE TITLE
d3-tip in Vue.js

### ISSUE THREAD

**Issue by Jesus82** [Caged/d3-tip#246]
Hi, I'm trying to use d3-tip in vue.js

My import statement is

```
import * as d3 from 'd3'
import d3Tip from "d3-tip";
d3.tip = d3Tip;
```

but I get the error `export 'tip' (imported as 'd3') was not found in 'd3'`

Has anyone make it work in vue.js? Thanks in advance!

**Comment by chenjieqianjinla** [comment]
ok，now？

**Comment by SeppPenner** [comment]
The library is no longer developed... https://github.com/Caged/d3-tip/issues/239#issuecomment-443053926.
