### ISSUE TITLE
Incorrect positioning of tooltip after scroll

### ISSUE THREAD

**Issue by n3integration** [Caged/d3-tip#39]
I have an SVG element being rendered at the bottom of a web page, which sometimes introduces vertical scrollbars where half of the element is visible before scrolling the page. When I mouse over a point on the SVG, the tooltip is being rendered well below the selected point. After tweaking the settings in `getScrollBBox` I am able to get better positioning, but it is still not perfect.

```
point.x = x + (scrollLeft / 2)
point.y = y + (scrollTop / 2)
```

Additional Information:

The `direction` is configured as `n`

**Comment by jarryd999** [comment]
I'm actually still getting this bug on windows 8 chrome Version 40.0.2214.91 m.  When at the top of the page, the positioning is fine.  However, when I scroll down, the tooltip is too high.
