### ISSUE TITLE
Tips overlaid on elements cause flickering

### ISSUE THREAD

**Issue by iwootten** [Caged/d3-tip#50]
Where a tip actually overlay elements, flicker occurs when hovering over portion of the tip overlaying the element. Presumably this is down to mouseover events being thrown on the tip itself and causing a mouseout on the element to which the tip is applied. I've had a look at issues 42 and 32 and the pointer-events:none solution doesn't resolve it.

I'm using chrome 32.01 but I'm seeing this issue in safari 7.01 and firefox 26 too. I'm using d3-tip v0.6.3 according to bower.

Here's an example (modified from previous ones): http://jsfiddle.net/6wGZB/1/

**Comment by jdylanstewart** [comment]
This worked for me so long as there is no space between `none` and `!important`.

So the CSS line would be `pointer-events: none!important;`
