### ISSUE TITLE
Option to follow cursor

### ISSUE THREAD

**Issue by wilg** [Caged/d3-tip#53]
I don't see an easy way to have the tooltip follow the cursor. I might fork and add this at some point, any guidance on the proper way would be useful.

**Comment by sinkpoint** [comment]
Just to add to the solution, since the recommendation had me scratching my heads for a while. 
Call ``` tip.show(data, circle.node()) ``` makes it work.

**Comment by Fil** [comment]
The solution is still not trivial (thanks @caged and @sinkpoint for pointing in the right direction).

Initialization step:
```
svg.append('circle').attr('id', 'tipfollowscursor')   /* .attr('r',5) /*  to debug */
svg.call(tip);
```

On targets:
```
        .on('mouseover', function (d) {
            var target = d3.select('#tipfollowscursor')
                .attr('cx', d3.event.offsetX)
                .attr('cy', d3.event.offsetY - 5) // 5 pixels above the cursor
                .node();
            tip.show(d, target);
        })
```
