### ISSUE TITLE
Firefox getScreenCTM bug?

### ISSUE THREAD

**Issue by tobinbradley** [Caged/d3-tip#56]
I'm having a problem with the tip placement in Firefox (28 and 27 tested). You can see the problem if you hover over a polygon on the map [here](http://mcmap.org/qol). The tip is down and to the right of the polygon. Hovering over the rects on the bar chart work fine. Chrome and IE work perfectly for the maps and chart, it's just Firefox that's the problem.

Take the furthest polygon on the map to the right. You can get where jQuery thinks it is on the page via `console.log($(".geom[data-id='396']").position().top, $(".geom[data-id='396']").position().left);`. Doing `console.log(coords.top, coords.left);` from within tip.show yields a much higher delta in Firefox.

Chrome/IE
jQuery top/left: 376/635
d3-tip top/left: 363/712 

Firefox
jQuery top/left: 416.75/636.25
d3-tip top/left: 483/789

It looks like the culprit is `getScreenCTM()` in getScreenBox. It's producing a very different result in Firefox. 'e' and 'f' in Chrome are 98 and 119, and they are 288 and 226 in Firefox for that furthest poly. I have no idea what e and f mean, so I could be wrong there.

So...kinda smells like a Firefox bug. I just wanted to check here to make sure I'm not doing something egregiously stupid before I go tromping through bugzilla :).

**Comment by Fil** [comment]
I notice the same problem. Not sure what to do — how would you incorporate the fix into d3.tip?

**Comment by GuyPie** [comment]
This was caused for me by using a transform on a parent container (wasn't a problem in Chrome)

**Comment by mattgabor** [comment]
Does anyone know a workaround? I am still experiencing this in FF.
