### ISSUE TITLE
Displaying tooltip programatically?

### ISSUE THREAD

**Issue by kenlimmj** [Caged/d3-tip#60]
Is there a way to display the tooltip (not on mouseover)?

Something of the nature of:

``` javascript
svg.select(".point").tooltip.show
```

to cause the tooltip to be displayed above the selected element?

**Comment by jamiewaese** [comment]
Did you ever figure out how to trigger you d3-tip tooltips programatically? I'm struggling with the same issue. The 'explicit-target' example does not explain it for me.

**Comment by kenlimmj** [comment]
I guess it's hard to say for individual cases, but following the recommendation above did the trick for me. It took a bit of mucking around because I had to correctly identify the element target (``pointElement``), but once I managed to select the item it worked as expected.

**Comment by jamiewaese** [comment]
Any chance you can send a link to your code?
