### ISSUE TITLE
Allow tooltip to be destroyed

### ISSUE THREAD

**Issue by ithinkdancan** [Caged/d3-tip#66]
I'm generating a dynamic number of charts in an Angular app and each has a tooltip. When I destroy the chart the tip is not getting removed from the DOM. Is there a way to properly destroy old tool tip instances?

**Comment by doganmeh** [comment]
I know this is an old issue, but for other people who may come accross: see [commit](https://github.com/rtidatascience/d3-tip/commit/e1001e076a6e5e8027530a2f8940c15206ddf180)
