### ISSUE TITLE
[feature] rename index.js

### ISSUE THREAD

**Issue by stryju** [Caged/d3-tip#68]
it would be nice to have a file different than `index.js` to more reflect the actual lib (`d3-tip.js` maybe?)

the reasoning behind this: every other lib does that and because of that it's easier to automate flattening the `bower_components` without really "cryptic" filename

**Comment by marcomusso** [comment]
:+1:

As a user I will gladly welcome a change of name just for standardization reasons (suppose I don't know what bower is :).

**Comment by M4urice** [comment]
+1

**Comment by inkbeard** [comment]
This doesn't seem fixed (at least with using npm) on the master branch.

@r4j4h, it unfortunately does effect a lot of people b/c if you're using NPM/bower to pull in 3rd party plugins and then use gulp, grunt, etc to copy the js file over, you would need to add another line of code to change the name appropriately. It's defeating the purpose of easily automation of multiple 3rd party plugins.

Any chance of opening this back up or should we open a new ticket? Thanks!

**Comment by vdh** [comment]
@inkbeard If you're trying to automate your module loading, it would be easier to provide assistance if you detailed what loader you're using. `d3-tip` already has support for both AMD and CommonJS, so if you're having loading issues, you'll need to be more specific. And yes, a new ticket would be better.

Module loaders (like Webpack, for example) are already set up to automate module loading via the `main` key in `package.json` or `bower.json` files. Javascript development is moving towards the ES6/ES2015 syntax for module loading, which supports directory indexes, so the filename of `index.js` could even be argued as more valid and discoverable than any other name.

**Comment by inkbeard** [comment]
@vdhm Thanks for the quick response. I'm going to _try_ to explain this is best as I can. Sorry if it's a bit lengthy, but maybe I'm just not setting this up correctly or it's the environment I'm working within. 

***

I see all the points you're making. It's not a matter of module loading (Currently using require for this), but this is more of a matter of getting the correct folder architecture for production/development environments.

Unfortunately I can't go into much detail but it's a pretty basic workflow that I've been using with npm/bower for a few years now:
1) Running npm `install d3-tip` and other various plugins
2) Use gulp to copy over the appropriate files to "local" folder to use with:
3) the require config.js file to point to appropriate js files.

I don't feel this is a very uncommon set up in the web/agency/app industry and to @marcomusso point, what if the user doesn't know what bower/npm is and if they're following your github instructions to download the latest dev version (also named `index.js`), it's more work for them to do unless it's named `d3-tip.js`. I think that yes, once everyone has adopted ES6, this will be easier, though that's a whole different story ;).

Again, maybe I'm doing this incorrectly, but based off of what I've done in the past with NPM/Bower along with the npm packages I've used, I feel like 95% of them are using a more appropriately named js file (or have a `/dist` folder). Maybe my use-case is a one off.

 I think this is a fantastic plugin and hope to continue using it for this and other d3 projects. Thanks.

**Comment by vdh** [comment]
@inkbeard That sounds like a hand-tailored bundling process, so if you're already doing that you should be tweaking names inside the Gulp copy tasks by hand as well. If you want a more streamlined process, consider switching to a more automated build tool (Webpack, Browserify, etc…). With or without NPM/Bower, manual bundling is _always_ going to create this kind of overhead. Your current experiences with "95% of" other filenames is just confirmation bias.

**Comment by inkbeard** [comment]
I hear you, sadly, in most jobs I've been in for the past 3-5 years, it's been a mixture of manual bundling with a bit of automation plugged in depending on their environments. I'll find an alternate way of getting this bundled up. Thanks for the response.
