### ISSUE TITLE
Support smart directions for elements near screen bounds

### ISSUE THREAD

**Issue by Caged** [Caged/d3-tip#8]
Sometimes tips can exceed the bounds of the screen.  For instance, if a `circle` element is at the `0,0` offset in the document and has a direction of `w`, the tooltip will be drawn off screen.  We should check for this and flip the direction to `e` in this case.

**Comment by Caged** [comment]
There's some related conversation here https://github.com/Caged/d3-tip/issues/117

**Comment by chrisknoll** [comment]
There looks like there's a pull request #153 for this but has conflicts. Is there a preferred approach to addressing this or will #153 be used as the solution?

**Comment by vlascik** [comment]
@chrisknoll I did a new PR for this, with conflicts solved, https://github.com/Caged/d3-tip/pull/198

**Comment by chrisknoll** [comment]
Buming this PR so that it does not look stale...
