### ISSUE TITLE
hidden tips block elements in IE9

### ISSUE THREAD

**Issue by mikeazo** [Caged/d3-tip#94]
In my IE9 testing, I found that if a tooltip covers up another element on the screen, when the tooltip is hidden, you can no longer click on that element or hover over it and get a tooltip.

Here is a [JSFiddle](http://jsfiddle.net/bLdukzn6/1/). In IE9, hover over the bottom circle, then try to hover over the circle just above it. The tooltip won't show up.

I was able to fix it by patching the hide and show methods. When the styles are set, I set *display:'inline'* on show and *display:'none'* on hide. That fixes it. Not sure if that causes any other issues, however.

**Comment by Caged** [comment]
Thanks for the report.  It looks like `pointer-events:all` is being set on the tooltip in `show` which is likely causing the issue.  Your fix should work just fine, but this sounds like a bug.

**Comment by mikeazo** [comment]
I found this: http://stackoverflow.com/questions/17441810/pointer-events-none-does-not-work-in-ie9-and-ie10

hide does set pointer-events to none.

**Comment by mikeazo** [comment]
I closed the pull request because I recently had a problem with it. To work around this bug, I ended up creating the tips programmatically and destroying them using jQuery.

**Comment by rjmorris** [comment]
@mikeazo, what problem did you have with your pull request? I was going to do something similar to fix this problem, except I was going to use `display: block` instead of `display: inline` in `show()`. Alternatively, I was considering using `visibility: hidden` and `visibility: visible`, which I think would also fix the problem.

I'll also note that this is still an issue in IE 10.

**Comment by mikeazo** [comment]
@rjmorris If I remember right, it is what is noted in #108. A hidden tooltip would block mouseover events.

**Comment by rjmorris** [comment]
Maybe I'm confused, but "a hidden tooltip blocking mouseover events" is the original subject of this issue. Your solution of setting `display: none` and `display: inline` fixed that. But then apparently you discovered a problem with that solution. I'm just wondering if you remember what that additional problem was.

**Comment by mikeazo** [comment]
@rjmorris Okay, sorry, it had just been a while. No, I don't remember what the issue was.

**Comment by rjmorris** [comment]
I decided to use `visibility: hidden/visible`, mainly because I didn't want to make assumptions about the `display` property. I haven't tested it extensively, but so far it's worked fine for me on IE 10, Chrome, and Firefox.

**Comment by Caged** [comment]
Closing as IE9 is EOL http://www.infoworld.com/article/3020534/security/microsoft-will-end-support-for-internet-explorer8-9-and-10.html
